import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React from "react";
import {
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useColors } from "@/hooks/useColors";

const LAST_UPDATED = "June 19, 2025";

const SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body: `By downloading, installing, or using Aura Wardrobe ("App," "Service"), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the App.

These Terms constitute a legally binding agreement between you and Aura Wardrobe. We reserve the right to update these Terms at any time. Continued use after changes constitutes acceptance.`,
  },
  {
    heading: "2. Use of the Service",
    body: `You may use Aura Wardrobe only for lawful, personal, non‑commercial purposes. You agree not to:

• Upload content that is illegal, harmful, or infringes on third‑party rights.
• Attempt to reverse engineer, decompile, or extract the source code of the App.
• Use automated bots or scrapers to interact with the Service.
• Circumvent authentication or security measures.
• Upload images of people without their consent.
• Use the AI features to generate harmful, discriminatory, or offensive content.`,
  },
  {
    heading: "3. AI‑Generated Recommendations Disclaimer",
    body: `The outfit suggestions, style recommendations, clothing analysis, and AI stylist responses provided by Aura Wardrobe are generated by artificial intelligence and are for informational and entertainment purposes only.

We make no warranty that AI suggestions are accurate, appropriate, or suitable for any specific occasion, environment, or individual. AI output may occasionally be incorrect, irrelevant, or inconsistent.

You are solely responsible for your clothing choices and any consequences thereof. Aura Wardrobe is not a professional fashion consultant.`,
  },
  {
    heading: "4. User‑Uploaded Content",
    body: `You retain ownership of all photos and content you upload to the App. By uploading content, you grant us a limited, non‑exclusive, royalty‑free license to process and analyze that content solely to provide the Service to you.

You represent and warrant that:
• You own or have the right to use all content you upload.
• Your content does not violate any third‑party intellectual property rights.
• Your content does not violate any applicable laws.

We do not use your clothing images to train AI models. Images submitted for analysis are processed and discarded per our AI provider's API data policy.`,
  },
  {
    heading: "5. Intellectual Property",
    body: `All content, design, code, trademarks, logos, and materials within Aura Wardrobe — excluding user‑uploaded content — are the exclusive property of Aura Wardrobe and its licensors.

You may not copy, reproduce, distribute, or create derivative works from any part of the Service without express written permission.`,
  },
  {
    heading: "6. Privacy",
    body: `Your use of the Service is governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our data practices.`,
  },
  {
    heading: "7. Account Responsibilities",
    body: `You are responsible for:
• Maintaining the confidentiality of your account credentials.
• All activity that occurs under your account.
• Notifying us immediately of any unauthorized account use.

We reserve the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or pose a security risk.`,
  },
  {
    heading: "8. Limitation of Liability",
    body: `To the maximum extent permitted by applicable law:

• Aura Wardrobe is provided "as is" without warranties of any kind, express or implied.
• We do not warrant that the Service will be uninterrupted, error‑free, or secure.
• We are not liable for any indirect, incidental, special, consequential, or punitive damages.
• Our total liability for any claim arising from your use of the Service shall not exceed the amount you paid for the Service in the 12 months preceding the claim (or $10 if you have not paid anything).

Some jurisdictions do not allow exclusion of certain warranties or limitations on liability. In such jurisdictions, our liability is limited to the greatest extent permitted by law.`,
  },
  {
    heading: "9. Termination",
    body: `You may stop using the App and delete your account at any time via Profile → Delete Account.

We may suspend or terminate your access if you violate these Terms, without prior notice. Upon termination:
• Your right to use the Service ceases immediately.
• We will delete your account data in accordance with our Privacy Policy.
• Provisions that by their nature survive termination (including intellectual property, limitation of liability, and dispute resolution) shall survive.`,
  },
  {
    heading: "10. Governing Law",
    body: `These Terms are governed by the laws of the applicable jurisdiction, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration or in the courts of the applicable jurisdiction.`,
  },
  {
    heading: "11. Contact",
    body: `For questions about these Terms:\n\nEmail: legal@aurawardrobe.app\nSupport: support@aurawardrobe.app`,
  },
];

export default function TermsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();

  const topPad = Platform.OS === "web" ? 20 : insets.top + 12;

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={[styles.header, { paddingTop: topPad }]}>
        <Pressable
          onPress={() => router.back()}
          style={[styles.backBtn, { backgroundColor: colors.secondary }]}
          hitSlop={12}
        >
          <Feather name="arrow-left" size={20} color={colors.foreground} />
        </Pressable>
        <Text style={[styles.headerTitle, { color: colors.foreground }]}>
          Terms & Conditions
        </Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={[
          styles.content,
          { paddingBottom: insets.bottom + 40 },
        ]}
      >
        <Text style={[styles.lastUpdated, { color: colors.mutedForeground }]}>
          Last updated: {LAST_UPDATED}
        </Text>
        <Text style={[styles.intro, { color: colors.mutedForeground }]}>
          Please read these Terms and Conditions carefully before using Aura
          Wardrobe. These terms govern your use of the application and related
          services.
        </Text>

        {SECTIONS.map((section) => (
          <View
            key={section.heading}
            style={[
              styles.section,
              { backgroundColor: colors.card, borderColor: colors.border },
            ]}
          >
            <Text style={[styles.sectionHeading, { color: colors.foreground }]}>
              {section.heading}
            </Text>
            <Text style={[styles.sectionBody, { color: colors.mutedForeground }]}>
              {section.body}
            </Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 17, fontFamily: "Inter_600SemiBold" },
  content: { paddingHorizontal: 20, gap: 12 },
  lastUpdated: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    marginBottom: 4,
  },
  intro: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    lineHeight: 21,
    textAlign: "center",
    marginBottom: 4,
  },
  section: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 8,
  },
  sectionHeading: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    lineHeight: 20,
  },
  sectionBody: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
  },
});
